/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":core"))
    api(libs.log4j.log4j)
}

description = "Server"
