/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots")
    }

    maven {
        url = uri("https://maven.pkg.github.com/Electroid/SportPaper")
    }

    maven {
        url = uri("https://jitpack.io/")
    }

    maven {
        url = uri("https://repo.viaversion.com/")
    }

    maven {
        url = uri("https://repo.pgm.fyi/snapshots")
    }

    maven {
        url = uri("https://repo.dmulloy2.net/repository/public/")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/maven-public/")
    }

    maven {
        url = uri("https://repo1.maven.org/maven2/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven("https://repo.papermc.io/repository/maven-public/")
}

dependencies {
    // Multi-protocol library for future Minecraft versions
    compileOnly("com.viaversion:viaversion-api:4.9.2")

    // Send packets to players
    compileOnly("com.comphenix.protocol:ProtocolLib:5.2.0-SNAPSHOT")

    implementation("org.jdom:jdom2:2.0.6.1")

    // Text library for creating messages in Minecraft
    implementation("net.kyori:adventure-api:4.15.0")
    implementation("net.kyori:adventure-text-serializer-plain:4.15.0")
    implementation("net.kyori:adventure-platform-bukkit:4.3.2") {
        exclude(group = "org.spigotmc", module = "spigot-api")
    }

    // Framework for defining and parsing commands
    implementation("cloud.commandframework:cloud-core:1.8.4")
    implementation("cloud.commandframework:cloud-annotations:1.8.4")
    implementation("cloud.commandframework:cloud-paper:1.8.4")
    implementation("cloud.commandframework:cloud-minecraft-extras:1.8.4")
    // Allows registering brigadier mappings
    implementation("me.lucko:commodore:2.2")

    // Small reflection library for Scoreboards
    implementation("fr.mrmicky:FastBoard:2.1.0")

    // Small reflection library for editing NBT
    implementation("io.github.bananapuncher714:nbteditor:7.19.2")

    // Framework for creating interactive GUIs - https://github.com/MinusKube/SmartInvs
    implementation("fr.minuskube.inv:smart-invs:1.2.7")

    implementation("com.github.cryptomorin:XSeries:9.4.0")

    // Git library for cloning and pulling repositories
    implementation("org.eclipse.jgit:org.eclipse.jgit:5.13.1.202206130422-r")

    // Simple mathematical expression evaluator library
    implementation("com.github.Pablete1234:exp4j:0431d412ec")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")

    annotationProcessor("cloud.commandframework:cloud-annotations:1.8.4")
}

group = "tc.oc.pgm"
version = "0.16-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}